### ISSUE TITLE
PM instead of AM in timestamps of miner proofs

### ISSUE THREAD

**Issue by MichaelZelbel** [agouin/0l-explorer#5]
Miner proofs that are submitted in the morning are timestamped with the right time, e.g. 11/7/2022, 7:53:10 but the wrong appendix, "PM" instead of "AM." See screenshot attached.

![minerproofpm](https://user-images.githubusercontent.com/102329247/200274754-c07f8a83-2b1e-47a0-98b7-0f3145e0091d.jpg)

**Comment by agouin** [comment]
This was due to the need to infer the transaction timestamp based on the transaction expiration since the transaction timestamp was not present from the diem-node json-rpc API. The expiration values are not always the same duration from the initial transaction. I made a change to the diem-node json-rpc API to expose the transaction timestamps directly.
